<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2016] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2016 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
?>
<?php
$parent = $this->getParentBlock();
$customer = $this->getCustomer();
$email = $customer->getEmail() ? $customer->getEmail() : $parent->getCustomerEmail()
?>

<!-- START REMARK -->
<?php if($this->getAllowedGlobalRemarkField()): ?>
    <h4>
        <?php echo Mage::helper('qquoteadv')->__('Remarks') ?>
    </h4>
    <div class="toggle-remark" id="toggle-remark-message" onclick="toggleRemark()">
        <span><?php echo $this->__('Add a note') ?></span><?php echo $this->__('with any special requests, shipping instructions, or other important details') ?>
    </div>
    <div class="remark-container" id="toggle-remark-container">
        <label for="customer:client_request">
            <?php echo $this->__('Do you have a general remark with your quote request?') ?>
        </label>
        <textarea name="customer[client_request]" id="customer:client_request" class="input-text">
            <?php echo $customer->getData('client_request'); ?>
        </textarea>
    </div>
<?php endif; ?>
<!-- END REMARK -->

<!-- QUOTE REFERENCE -->
<?php if($this->getAllowQuoteReference()):?>
    <label for="customer:quote_reference"><?php echo $this->__('Quote reference') ?></label>
    <?php echo $this->getFieldRequiredSpan($this->getQuoteReference()); ?>
    <input name="customer[quote_reference]"
           id="customer:quote_reference"
           cols="10" rows="5"
           style="width:95%;"
           class="input-text <?php $this->getFieldRequiredClass($this->getQuoteReference()) ?>"
           value="<?php echo $customer->getData('quote_reference'); ?>"/>
<?php endif;?>
<!-- END QUOTE REFERENCE -->

<?php if ($parent->isCustomerLoggedIn() && !empty($billingEmail)): ?>
<div id="billing-new-address-form" style="display:none;">
    <?php else: ?>
    <div class="input-box">
        <?php endif; ?>
        <div id="accountDiv">

            <table id="qquote-tbl-address" cellspacing='6' cellpadding='3' border="0" width="100%">
                <tr>
                    <!-- START EMAIL -->
                    <td class="fullWidth">
                        <label for="customer:email">
                            <?php echo Mage::helper('sales')->__('Email Address') ?>
                        </label>
                        <span class="required"></span>
                        <input <?php if (!empty($email)): ?>readonly<?php endif; ?> type='text'
                               value="<?php echo $email; ?>"
                               name='customer[email]' id='customer:email'
                               class="disabled validate-email required-entry input-text"/><span id="please-wait"
                                                                                       style="display:none;"><img
                                alt="<?php echo $parent->__('Checking..') ?>"
                                src="<?php echo $parent->getSkinUrl('images/ajax-loader.gif') ?>"/></span>

                        <div style="display:none;" id="email_message">&nbsp;</div>
                    </td>
                    <!-- END EMAIL -->
                    <td class="p5">
                    </td>
                </tr>
                <!-- START EXTRA FIELDS -->
                <?php if(Mage::app()->getHelper('qquoteadv/licensechecks')->isAllowedCustomFields()):?>
                    <?php echo $parent->getChildHtml('qquote.extrafields'); ?>
                <?php endif; ?>
                <!-- END EXTRA FIELDS -->
            </table>
        </div>
        <!-- START NEWSLETTER -->
        <?php if (Mage::getStoreConfig('qquoteadv_quote_form_builder/options/newsletter_subscribe')): ?>
            <div class="checkbox-container">
                <input id="chkNews" type="checkbox" name="newsletter">
                <label for="chkNews" class="checkbox">
                    <span><?php echo Mage::helper('newsletter')->__('Sign up for our newsletter'); ?></span>
                </label>
            </div>
        <?php endif; ?>
        <!-- END NEWSLETTER -->
    </div>
